[build]
  command = "pip install -r requirements.txt"
  publish = "src/frontend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 