[build]
  publish = "src/frontend"
  command = "echo 'Static site - no build required'"

[[redirects]]
  from = "/api/*"
  to = "https://policiamilitarnovacapital.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 